# Type Path                         Mode User  Group Age Argument
d /var/lib/helix                    0700 helix helix -   -
d /var/lib/helix/state              0700 helix helix -   -
d /var/lib/helix/metrics            0700 helix helix -   -
d /var/cache/helix                  0700 helix helix -   -
d /run/helix                        0700 helix helix -   -
