import type { GameHostingReadiness, GameInstanceSummary } from './game-types';

export const visualGameReadiness: GameHostingReadiness = {
  schemaVersion: 1,
  availability: 'degraded',
  availableFeatures: ['instances.view'],
  blockers: [
    { code: 'verified_restore', status: 'ready' },
    { code: 'privileged_broker', status: 'in_progress' },
    { code: 'native_execution', status: 'required' },
  ],
  collectedAtUnixMs: 1_787_756_400_000,
};

export const visualGameInstances: GameInstanceSummary[] = [
  {
    id: '118f8fcb-b7af-4f13-9f56-0559788b2c56',
    name: 'Survival SMP',
    game: 'Minecraft',
    software: 'Paper',
    version: 'Visual fixture',
    status: 'online',
    health: 'healthy',
    playersOnline: 18,
    playersMax: 40,
    cpuPercent: 38.4,
    memoryUsedBytes: 6_442_450_944,
    memoryLimitBytes: 8_589_934_592,
    uptimeSeconds: 372_300,
    address: 'play.example.test:25565',
    updateStatus: 'current',
    backupStatus: 'healthy',
    warnings: [],
    features: [
      'console',
      'players',
      'settings',
      'mods_plugins',
      'worlds_saves',
      'files',
      'networking',
      'backups',
      'automation',
      'logs',
      'performance',
      'advanced',
    ],
  },
  {
    id: '228f8fcb-b7af-4f13-9f56-0559788b2c57',
    name: 'Creative Lab',
    game: 'Minecraft',
    software: 'Vanilla',
    version: 'Visual fixture',
    status: 'offline',
    health: 'unknown',
    playersOnline: 0,
    playersMax: 12,
    cpuPercent: null,
    memoryUsedBytes: null,
    memoryLimitBytes: 4_294_967_296,
    uptimeSeconds: null,
    address: '192.0.2.10:25566',
    updateStatus: 'pinned',
    backupStatus: 'healthy',
    warnings: [],
    features: ['console', 'players', 'settings', 'worlds_saves', 'files', 'networking', 'backups', 'logs', 'advanced'],
  },
  {
    id: '338f8fcb-b7af-4f13-9f56-0559788b2c58',
    name: 'Night Shift',
    game: 'V Rising',
    software: 'Dedicated server',
    version: 'Visual fixture',
    status: 'degraded',
    health: 'degraded',
    playersOnline: 6,
    playersMax: 20,
    cpuPercent: 22.1,
    memoryUsedBytes: 3_274_180_608,
    memoryLimitBytes: 6_442_450_944,
    uptimeSeconds: 86_700,
    address: '192.0.2.10:27015',
    updateStatus: 'available',
    backupStatus: 'stale',
    warnings: ['Last verified backup is outside policy.', 'An update is available.'],
    features: ['console', 'players', 'settings', 'worlds_saves', 'files', 'networking', 'backups', 'automation', 'logs', 'performance', 'advanced'],
  },
  {
    id: '448f8fcb-b7af-4f13-9f56-0559788b2c59',
    name: 'Weekend Factory',
    game: 'Satisfactory',
    software: 'Dedicated server',
    version: 'Visual fixture',
    status: 'updating',
    health: 'healthy',
    playersOnline: 0,
    playersMax: 8,
    cpuPercent: 5.2,
    memoryUsedBytes: 2_147_483_648,
    memoryLimitBytes: 8_589_934_592,
    uptimeSeconds: null,
    address: '192.0.2.10:7777',
    updateStatus: 'checking',
    backupStatus: 'healthy',
    warnings: [],
    features: ['console', 'players', 'settings', 'worlds_saves', 'files', 'networking', 'backups', 'automation', 'logs', 'performance', 'advanced'],
  },
];
