type Message = string | ((...args: never[]) => string);

const englishMessages = {
  'common.colorTheme': 'Color theme',
  'common.source': 'Source',
  'common.sourceAndLicense': 'Source & license',
  'common.tryAgain': 'Try again',
  'theme.system': 'System',
  'theme.midnight': 'Midnight',
  'theme.oled': 'OLED',
  'theme.light': 'Light',

  'auth.error.fallback': 'Helix could not complete that request.',
  'auth.skipToForm': 'Skip to form',
  'auth.loading.eyebrow': 'Secure local session',
  'auth.loading.title': 'Connecting to Helix',
  'auth.loading.detail': 'Checking setup and session state.',
  'auth.unavailable.eyebrow': 'Connection unavailable',
  'auth.unavailable.title': 'Helix did not respond',
  'auth.setup.eyebrow': 'First run · owner account',
  'auth.setup.title': 'Make this Helix yours.',
  'auth.setup.instructionsBeforeCommand': 'Generate a short-lived token with',
  'auth.setup.instructionsAfterCommand':
    'on the server, then create the only founding owner account.',
  'auth.setup.noToken':
    'No active setup token. Generate one in the server terminal; it expires after 15 minutes and a newer token invalidates the old one.',
  'auth.setup.token': 'Setup token',
  'auth.setup.loginName': 'Login name',
  'auth.setup.displayName': 'Display name',
  'auth.setup.displayNameHelp':
    'Use 1–128 characters. The server also applies a UTF-8 size limit.',
  'auth.setup.password': 'Owner password',
  'auth.setup.passwordHelp':
    'Use 15–256 characters. Avoid Helix, your login or display name, obvious repetition, and common passwords. Spaces and Unicode are supported.',
  'auth.setup.confirmPassword': 'Confirm password',
  'auth.setup.submit': 'Create owner and continue',
  'auth.setup.submitting': 'Creating owner…',
  'auth.setup.footnote':
    'The setup token is consumed atomically. Your password is never stored in browser storage.',
  'auth.setup.error.passwordMismatch': 'The password confirmation does not match.',
  'auth.setup.error.bootstrapToken':
    'Enter the 43-character setup token generated by helixctl.',
  'auth.setup.error.loginName':
    'Use 3–64 lowercase letters, numbers, dots, underscores, or hyphens, starting and ending with a letter or number.',
  'auth.setup.error.passwordTooShort':
    'Use at least 13 characters for the owner password.',
  'auth.setup.error.passwordTooLong':
    'Use no more than 256 characters for the owner password.',
  'auth.setup.error.passwordTooLarge':
    'Use a shorter password; the server also applies a UTF-8 size limit.',
  'auth.setup.error.displayNameLength':
    'Use a display name between 1 and 128 characters.',
  'auth.setup.error.displayNameTooLarge':
    'Use a shorter display name; the server also applies a UTF-8 size limit.',
  'auth.setup.error.displayNameWhitespace':
    'Remove whitespace from the beginning or end of the display name.',
  'auth.setup.error.displayNameControl':
    'The display name cannot contain control characters.',
  'auth.login.eyebrow': 'Local control plane',
  'auth.login.title': 'Welcome back.',
  'auth.login.detail': "Sign in to see this server's live Helix dashboard.",
  'auth.login.loginName': 'Login name',
  'auth.login.password': 'Password',
  'auth.login.submit': 'Sign in',
  'auth.login.submitting': 'Signing in…',
  'auth.login.footnote': 'Sessions expire after 30 minutes idle and eight hours at most.',
  'auth.login.notice.sessionExpired':
    'Your Helix session expired or was revoked. Sign in again.',
  'auth.login.notice.setupCompleted':
    'Owner setup was completed in another session. Sign in to continue.',
  'auth.login.notice.accountUpdated':
    'Account updated. Sign in again with the updated credentials.',

} as const;

export type TranslationId = keyof typeof englishMessages;

type TranslationArgs<Id extends TranslationId> =
  (typeof englishMessages)[Id] extends (...args: infer Args) => string ? Args : [];

export function t<Id extends TranslationId>(
  id: Id,
  ...args: TranslationArgs<Id>
): string {
  const message: Message = englishMessages[id] as Message;
  if (typeof message === 'function') {
    return (message as (...values: TranslationArgs<Id>) => string)(...args);
  }
  return message;
}
