type Message = string | ((...args: never[]) => string);

const englishMessages = {
  'common.colorTheme': 'Color theme',
  'common.tryAgain': 'Try again',
  'theme.system': 'System',
  'theme.midnight': 'Midnight',
  'theme.oled': 'OLED',
  'theme.light': 'Light',

  'auth.error.fallback': 'Helix could not complete that request.',
  'auth.skipToForm': 'Skip to form',
  'auth.loading.eyebrow': 'Secure local session',
  'auth.loading.title': 'Connecting to Helix',
  'auth.loading.detail': 'Checking setup and session state.',
  'auth.unavailable.eyebrow': 'Connection unavailable',
  'auth.unavailable.title': 'Helix did not respond',
  'auth.setup.eyebrow': 'First run · owner account',
  'auth.setup.title': 'Make this Helix yours.',
  'auth.setup.instructionsBeforeCommand': 'Generate a short-lived token with',
  'auth.setup.instructionsAfterCommand':
    'on the server, then create the only founding owner account.',
  'auth.setup.noToken':
    'No active setup token. Generate one in the server terminal; it expires after 15 minutes and a newer token invalidates the old one.',
  'auth.setup.token': 'Setup token',
  'auth.setup.loginName': 'Login name',
  'auth.setup.displayName': 'Display name',
  'auth.setup.displayNameHelp':
    'Use 1–128 characters. The server also applies a UTF-8 size limit.',
  'auth.setup.password': 'Owner password',
  'auth.setup.passwordHelp':
    'Use 15–256 characters. Avoid Helix, your login or display name, obvious repetition, and common passwords. Spaces and Unicode are supported.',
  'auth.setup.confirmPassword': 'Confirm password',
  'auth.setup.submit': 'Create owner and continue',
  'auth.setup.submitting': 'Creating owner…',
  'auth.setup.footnote':
    'The setup token is consumed atomically. Your password is never stored in browser storage.',
  'auth.setup.error.passwordMismatch': 'The password confirmation does not match.',
  'auth.setup.error.bootstrapToken':
    'Enter the 43-character setup token generated by helixctl.',
  'auth.setup.error.loginName':
    'Use 3–64 lowercase letters, numbers, dots, underscores, or hyphens, starting and ending with a letter or number.',
  'auth.setup.error.passwordTooShort':
    'Use at least 15 characters for the owner password.',
  'auth.setup.error.passwordTooLong':
    'Use no more than 256 characters for the owner password.',
  'auth.setup.error.passwordTooLarge':
    'Use a shorter password; the server also applies a UTF-8 size limit.',
  'auth.setup.error.displayNameLength':
    'Use a display name between 1 and 128 characters.',
  'auth.setup.error.displayNameTooLarge':
    'Use a shorter display name; the server also applies a UTF-8 size limit.',
  'auth.setup.error.displayNameWhitespace':
    'Remove whitespace from the beginning or end of the display name.',
  'auth.setup.error.displayNameControl':
    'The display name cannot contain control characters.',
  'auth.login.eyebrow': 'Local control plane',
  'auth.login.title': 'Welcome back.',
  'auth.login.detail': "Sign in to see this server's live Helix dashboard.",
  'auth.login.loginName': 'Login name',
  'auth.login.password': 'Password',
  'auth.login.submit': 'Sign in',
  'auth.login.submitting': 'Signing in…',
  'auth.login.footnote': 'Sessions expire after 30 minutes idle and eight hours at most.',
  'auth.login.notice.sessionExpired':
    'Your Helix session expired or was revoked. Sign in again.',
  'auth.login.notice.setupCompleted':
    'Owner setup was completed in another session. Sign in to continue.',

  'dashboard.error.fallback': 'Helix could not load this data.',
  'dashboard.skipToMain': 'Skip to main content',
  'dashboard.brandOverview': 'Helix overview',
  'dashboard.navigation': 'Dashboard sections',
  'dashboard.nav.overview': 'Overview',
  'dashboard.nav.health': 'Health',
  'dashboard.nav.host': 'Host',
  'dashboard.nav.storage': 'Storage',
  'dashboard.nav.network': 'Network',
  'dashboard.controlPlane': 'Control plane',
  'dashboard.status.lastKnown': 'Last known status',
  'dashboard.status.refreshFailed': 'Refresh failed',
  'dashboard.status.operational': 'All reported systems operational',
  'dashboard.status.attention': 'Attention reported by Helix',
  'dashboard.status.unavailable': 'Unavailable',
  'dashboard.status.healthUnavailable': 'Health API did not respond',
  'dashboard.status.connecting': 'Connecting',
  'dashboard.status.waiting': 'Waiting for health API',
  'dashboard.loadingMetric': 'Loading metric',
  'dashboard.loadingDetails': 'Loading details',
  'dashboard.resourceUnavailable': (label: string) => `${label} unavailable.`,
  'dashboard.resourceStale': (label: string) =>
    `Showing the last ${label.toLowerCase()} sample.`,
  'dashboard.metricAria': (label: string, value: string) => `${label}: ${value}`,
  'dashboard.metric.cpu': 'CPU usage',
  'dashboard.metric.memory': 'Memory',
  'dashboard.metric.uptime': 'Uptime',
  'dashboard.metric.swap': 'Swap',
  'dashboard.metric.unavailableDetail': 'System overview did not load',
  'dashboard.metric.cpuSampling': 'Sampling…',
  'dashboard.metric.cpuWaiting': 'Waiting for a second valid sample',
  'dashboard.metric.logicalCores': (count: number) =>
    `${count} logical ${count === 1 ? 'core' : 'cores'}`,
  'dashboard.metric.notReported': 'Not reported',
  'dashboard.metric.zeroMemory': 'Host reported zero total memory',
  'dashboard.metric.usedOfTotal': (used: string, total: string) => `${used} of ${total}`,
  'dashboard.metric.reportedByHost': 'Reported by the host',
  'dashboard.metric.swapNotConfigured': 'Not configured',
  'dashboard.metric.noSwap': 'No swap space reported',
  'dashboard.health.title': 'Health',
  'dashboard.health.detailsUnavailable': 'Health details unavailable',
  'dashboard.health.noValues': 'No health values are being shown.',
  'dashboard.health.apiStatus': 'API status',
  'dashboard.health.stateDatabase': 'State database',
  'dashboard.health.metricsDatabase': 'Metrics database',
  'dashboard.health.version': 'Helix version',
  'dashboard.health.checked': 'Checked',
  'dashboard.host.eyebrow': 'Environment',
  'dashboard.host.title': 'Host',
  'dashboard.host.detailsUnavailable': 'Host details unavailable',
  'dashboard.host.noValues': 'No host values are being shown.',
  'dashboard.host.hostname': 'Hostname',
  'dashboard.host.operatingSystem': 'Operating system',
  'dashboard.host.architecture': 'Architecture',
  'dashboard.host.kernel': 'Kernel',
  'dashboard.host.logicalCores': 'Logical cores',
  'dashboard.host.availableMemory': 'Available memory',
  'dashboard.host.sampled': 'Sampled',
  'dashboard.discovery.available': 'Available',
  'dashboard.discovery.degraded': 'Partial',
  'dashboard.discovery.unavailable': 'Unavailable',
  'dashboard.discovery.partial': 'Some host discovery data was omitted.',
  'dashboard.storage.eyebrow': 'Capacity',
  'dashboard.storage.title': 'Storage',
  'dashboard.storage.detailsUnavailable': 'Storage details unavailable',
  'dashboard.storage.noValues': 'No storage values are being shown.',
  'dashboard.storage.unavailable': 'Storage discovery unavailable',
  'dashboard.storage.unavailableDetail':
    'This platform did not provide a supported storage collector.',
  'dashboard.storage.noMounts': 'No mounted storage reported',
  'dashboard.storage.noMountsDetail':
    'The collector completed without returning a mounted volume.',
  'dashboard.storage.mountCount': (count: number) =>
    `${count} ${count === 1 ? 'mount' : 'mounts'} shown`,
  'dashboard.storage.omittedMounts': (count: number) =>
    `${count} additional ${count === 1 ? 'mount was' : 'mounts were'} omitted by the response limit.`,
  'dashboard.storage.omittedText': (count: number) =>
    `${count} host text ${count === 1 ? 'field could' : 'fields could'} not be represented safely.`,
  'dashboard.storage.unknownMount': 'Unnamed mount',
  'dashboard.storage.device': 'Device',
  'dashboard.storage.fileSystem': 'File system',
  'dashboard.storage.mountPoint': 'Mount point',
  'dashboard.storage.capacity': 'Capacity used',
  'dashboard.storage.available': 'Available',
  'dashboard.storage.readOnly': 'Read only',
  'dashboard.storage.removable': 'Removable',
  'dashboard.common.yes': 'Yes',
  'dashboard.common.no': 'No',
  'dashboard.network.eyebrow': 'Connectivity',
  'dashboard.network.title': 'Network',
  'dashboard.network.detailsUnavailable': 'Network details unavailable',
  'dashboard.network.noValues': 'No network values are being shown.',
  'dashboard.network.unavailable': 'Network discovery unavailable',
  'dashboard.network.unavailableDetail':
    'This platform did not provide a supported network collector.',
  'dashboard.network.noInterfaces': 'No network interfaces reported',
  'dashboard.network.noInterfacesDetail':
    'The collector completed without returning an interface.',
  'dashboard.network.interfaceCount': (count: number) =>
    `${count} ${count === 1 ? 'interface' : 'interfaces'} shown`,
  'dashboard.network.omittedInterfaces': (count: number) =>
    `${count} additional ${count === 1 ? 'interface was' : 'interfaces were'} omitted by the response limit.`,
  'dashboard.network.omittedAddresses': (count: number) =>
    `${count} additional ${count === 1 ? 'address was' : 'addresses were'} omitted by the response limit.`,
  'dashboard.network.addresses': 'Addresses',
  'dashboard.network.noAddresses': 'No addresses reported',
  'dashboard.network.received': 'Received total',
  'dashboard.network.transmitted': 'Sent total',
  'dashboard.network.cumulativeHelp': 'Cumulative host counters, not transfer rates',
  'dashboard.network.mtu': 'MTU',
  'dashboard.localServer': 'Local server',
  'dashboard.signedInAs': (loginName: string) => `Signed in as ${loginName}`,
  'dashboard.refresh': 'Refresh',
  'dashboard.refreshing': 'Refreshing',
  'dashboard.signOut': 'Sign out',
  'dashboard.signingOut': 'Signing out',
  'dashboard.hero.eyebrow': 'Live system overview',
  'dashboard.hero.titleBefore': 'Your server,',
  'dashboard.hero.titleAfter': 'clearly in view.',
  'dashboard.hero.detail':
    'A quiet, local-first control surface. Every value below comes directly from this Helix host.',
  'dashboard.hero.currentStatus': 'Current status',
  'dashboard.hero.refreshCadence': 'Refresh cadence',
  'dashboard.hero.refreshVisible': '30s while visible',
  'dashboard.systemOverview': 'System overview',
  'dashboard.refreshAnnouncement': 'Refreshing Helix data.',
  'dashboard.footer.phase': 'Helix Phase 1',
  'dashboard.footer.localFirst': 'Local-first by design',
} as const;

export type TranslationId = keyof typeof englishMessages;

type TranslationArgs<Id extends TranslationId> =
  (typeof englishMessages)[Id] extends (...args: infer Args) => string ? Args : [];

export function t<Id extends TranslationId>(
  id: Id,
  ...args: TranslationArgs<Id>
): string {
  const message: Message = englishMessages[id] as Message;
  if (typeof message === 'function') {
    return (message as (...values: TranslationArgs<Id>) => string)(...args);
  }
  return message;
}
